{"name": "test_create_order_success", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(@class, 'Input_Responsible') and text()='* Имя']\"}\n  (Session info: headless chrome=119.0.6045.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104e2e004 chromedriver + 4169732\n1   chromedriver                        0x0000000104e25ff8 chromedriver + 4136952\n2   chromedriver                        0x0000000104a7b500 chromedriver + 292096\n3   chromedriver                        0x0000000104ac07a0 chromedriver + 575392\n4   chromedriver                        0x0000000104afb818 chromedriver + 817176\n5   chromedriver                        0x0000000104ab45e8 chromedriver + 525800\n6   chromedriver                        0x0000000104ab54b8 chromedriver + 529592\n7   chromedriver                        0x0000000104df4334 chromedriver + 3932980\n8   chromedriver                        0x0000000104df8970 chromedriver + 3950960\n9   chromedriver                        0x0000000104ddc774 chromedriver + 3835764\n10  chromedriver                        0x0000000104df9478 chromedriver + 3953784\n11  chromedriver                        0x0000000104dceab4 chromedriver + 3779252\n12  chromedriver                        0x0000000104e15914 chromedriver + 4069652\n13  chromedriver                        0x0000000104e15a90 chromedriver + 4070032\n14  chromedriver                        0x0000000104e25c70 chromedriver + 4136048\n15  libsystem_pthread.dylib             0x0000000192603fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001925feda0 thread_start + 8", "trace": "self = <tests.test_order_page.TestOrderPage object at 0x102c751d0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"80e1f21a22a29ef07bf7b7a86780ce2a\")>\n\n    def test_create_order_success(self, driver):\n>       OrderPage(driver).create_order()\n\ntests/test_order_page.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/order_page.py:69: in create_order\n    self.set_name_to_field(first_name)\npages/order_page.py:14: in set_name_to_field\n    self.set_text_to_element(OrderPageLocators.NAME_FLD_LOCATOR, text)\npages/base_page.py:25: in set_text_to_element\n    self.driver.find_element(*locator).send_keys(text)\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x102c77e10>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...000192603fa8 _pthread_start + 148\\\\n16  libsystem_pthread.dylib             0x00000001925feda0 thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(@class, 'Input_Responsible') and text()='* Имя']\"}\nE         (Session info: headless chrome=119.0.6045.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x0000000104e2e004 chromedriver + 4169732\nE       1   chromedriver                        0x0000000104e25ff8 chromedriver + 4136952\nE       2   chromedriver                        0x0000000104a7b500 chromedriver + 292096\nE       3   chromedriver                        0x0000000104ac07a0 chromedriver + 575392\nE       4   chromedriver                        0x0000000104afb818 chromedriver + 817176\nE       5   chromedriver                        0x0000000104ab45e8 chromedriver + 525800\nE       6   chromedriver                        0x0000000104ab54b8 chromedriver + 529592\nE       7   chromedriver                        0x0000000104df4334 chromedriver + 3932980\nE       8   chromedriver                        0x0000000104df8970 chromedriver + 3950960\nE       9   chromedriver                        0x0000000104ddc774 chromedriver + 3835764\nE       10  chromedriver                        0x0000000104df9478 chromedriver + 3953784\nE       11  chromedriver                        0x0000000104dceab4 chromedriver + 3779252\nE       12  chromedriver                        0x0000000104e15914 chromedriver + 4069652\nE       13  chromedriver                        0x0000000104e15a90 chromedriver + 4070032\nE       14  chromedriver                        0x0000000104e25c70 chromedriver + 4136048\nE       15  libsystem_pthread.dylib             0x0000000192603fa8 _pthread_start + 148\nE       16  libsystem_pthread.dylib             0x00000001925feda0 thread_start + 8\n\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "steps": [{"name": "Create order", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(@class, 'Input_Responsible') and text()='* Имя']\"}\n  (Session info: headless chrome=119.0.6045.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104e2e004 chromedriver + 4169732\n1   chromedriver                        0x0000000104e25ff8 chromedriver + 4136952\n2   chromedriver                        0x0000000104a7b500 chromedriver + 292096\n3   chromedriver                        0x0000000104ac07a0 chromedriver + 575392\n4   chromedriver                        0x0000000104afb818 chromedriver + 817176\n5   chromedriver                        0x0000000104ab45e8 chromedriver + 525800\n6   chromedriver                        0x0000000104ab54b8 chromedriver + 529592\n7   chromedriver                        0x0000000104df4334 chromedriver + 3932980\n8   chromedriver                        0x0000000104df8970 chromedriver + 3950960\n9   chromedriver                        0x0000000104ddc774 chromedriver + 3835764\n10  chromedriver                        0x0000000104df9478 chromedriver + 3953784\n11  chromedriver                        0x0000000104dceab4 chromedriver + 3779252\n12  chromedriver                        0x0000000104e15914 chromedriver + 4069652\n13  chromedriver                        0x0000000104e15a90 chromedriver + 4070032\n14  chromedriver                        0x0000000104e25c70 chromedriver + 4136048\n15  libsystem_pthread.dylib             0x0000000192603fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001925feda0 thread_start + 8\n\n", "trace": "  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/pages/order_page.py\", line 69, in create_order\n    self.set_name_to_field(first_name)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/pages/order_page.py\", line 14, in set_name_to_field\n    self.set_text_to_element(OrderPageLocators.NAME_FLD_LOCATOR, text)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/pages/base_page.py\", line 25, in set_text_to_element\n    self.driver.find_element(*locator).send_keys(text)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Fill name field", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[contains(@class, 'Input_Responsible') and text()='* Имя']\"}\n  (Session info: headless chrome=119.0.6045.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104e2e004 chromedriver + 4169732\n1   chromedriver                        0x0000000104e25ff8 chromedriver + 4136952\n2   chromedriver                        0x0000000104a7b500 chromedriver + 292096\n3   chromedriver                        0x0000000104ac07a0 chromedriver + 575392\n4   chromedriver                        0x0000000104afb818 chromedriver + 817176\n5   chromedriver                        0x0000000104ab45e8 chromedriver + 525800\n6   chromedriver                        0x0000000104ab54b8 chromedriver + 529592\n7   chromedriver                        0x0000000104df4334 chromedriver + 3932980\n8   chromedriver                        0x0000000104df8970 chromedriver + 3950960\n9   chromedriver                        0x0000000104ddc774 chromedriver + 3835764\n10  chromedriver                        0x0000000104df9478 chromedriver + 3953784\n11  chromedriver                        0x0000000104dceab4 chromedriver + 3779252\n12  chromedriver                        0x0000000104e15914 chromedriver + 4069652\n13  chromedriver                        0x0000000104e15a90 chromedriver + 4070032\n14  chromedriver                        0x0000000104e25c70 chromedriver + 4136048\n15  libsystem_pthread.dylib             0x0000000192603fa8 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001925feda0 thread_start + 8\n\n", "trace": "  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/pages/order_page.py\", line 14, in set_name_to_field\n    self.set_text_to_element(OrderPageLocators.NAME_FLD_LOCATOR, text)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/pages/base_page.py\", line 25, in set_text_to_element\n    self.driver.find_element(*locator).send_keys(text)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/qa_python_6/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "text", "value": "'Евстигней'"}], "start": 1699963893253, "stop": 1699963893262}], "start": 1699963893253, "stop": 1699963893264}], "start": 1699963893253, "stop": 1699963893265, "uuid": "76545f6a-182d-4314-b654-6ae2139e7fc6", "historyId": "8f5bdbe36c9358057ac2cc0e6097a4f7", "testCaseId": "8f5bdbe36c9358057ac2cc0e6097a4f7", "fullName": "tests.test_order_page.TestOrderPage#test_create_order_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_page"}, {"name": "subSuite", "value": "TestOrderPage"}, {"name": "host", "value": "MacBook-Air-Aleksej.local"}, {"name": "thread", "value": "16720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_page"}]}